name: cards
description: A card game.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^0.2.0
  cloud_firestore: ^0.8.0
  flutter_mailer: ^0.1.0
  google_sign_in: ^3.0.5
  hex: ^0.1.1
  rxdart: ^0.18.0
  shared_preferences: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Bitter
      fonts:
        - asset: fonts/Bitter-Regular.ttf
    - family: Assistant
      fonts:
        - asset: fonts/Assistant-ExtraBold.ttf

  assets:
    - assets/de/
    - graphics/
