name: cards
description: A card game.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^0.2.0
  cloud_firestore: ^0.8.0
  firebase_auth: any
  google_sign_in: ^3.0.5
  hex: ^0.1.1
  rxdart: ^0.18.0
  shared_preferences: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Signature
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: fonts/Ubuntu-Bold.ttf
          weight: 700

  assets:
    - assets/de/
    - graphics/
