enum _TextType {
  TITLE,
  CONFIGURATION_NAMES_EMPTY_STATE,
  CONFIGURATION_NAME_INPUT_LABEL,
  CONFIGURATION_NAME_INPUT_HINT,
  CONFIGURATION_NAME_INPUT_ERROR,
  CONFIGURATION_DECKS_EMPTY_STATE,
  CONFIGURATION_FAB_ADD_PLAYER,
  CONFIGURATION_FAB_ADD_DECK,
  CONFIGURATION_FAB_START,
  MENU_MY_CARDS,
  MENU_SEND_FEEDBACK,
  CARD_AUTHOR
}
